<?xml version="1.0" encoding="utf-8"?><Database Name="PowerLook" Class="PowerLookDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=PowerLook;Integrated Security=True" SettingsObjectName="DBPowerLook.DAL.Properties.Settings" SettingsPropertyName="PowerLookConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Fornecedores" Member="Fornecedores">
    <Type Name="Fornecedores">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome_fantasia" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="telefone" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="id_pessoa_juridica" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="complemento" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="numero_casa" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="id_endereco" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Fornecedores_Produtos" Member="Produtos" ThisKey="id" OtherKey="id_fornecedor" Type="Produtos" />
      <Association Name="Enderecos_Fornecedores" Member="Enderecos" ThisKey="id_endereco" OtherKey="id" Type="Enderecos" IsForeignKey="true" />
      <Association Name="PessoaJurifica_Fornecedores" Member="PessoaJurifica" ThisKey="id_pessoa_juridica" OtherKey="id" Type="PessoaJurifica" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Locacoes" Member="Locacoes">
    <Type Name="Locacoes">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PessoaFisica" Member="PessoaFisica">
    <Type Name="PessoaFisica">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cpf" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="rg" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="PessoaFisica_Usuarios" Member="Usuarios" ThisKey="id" OtherKey="id_pessoa_fisica" Type="Usuarios" />
    </Type>
  </Table>
  <Table Name="dbo.Enderecos" Member="Enderecos">
    <Type Name="Enderecos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cep" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="endereco" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="bairro" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="cidade" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="uf" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Enderecos_Fornecedores" Member="Fornecedores" ThisKey="id" OtherKey="id_endereco" Type="Fornecedores" />
      <Association Name="Enderecos_Usuarios" Member="Usuarios" ThisKey="id" OtherKey="id_endereco" Type="Usuarios" />
    </Type>
  </Table>
  <Table Name="dbo.PessoaJurifica" Member="PessoaJurifica">
    <Type Name="PessoaJurifica">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cnpj" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="inscricao_estadual" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="razao_social" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="PessoaJurifica_Fornecedores" Member="Fornecedores" ThisKey="id" OtherKey="id_pessoa_juridica" Type="Fornecedores" />
    </Type>
  </Table>
  <Table Name="dbo.Produtos" Member="Produtos">
    <Type Name="Produtos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="tamanho" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="tipo_manga" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="tipo_decote" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="cor" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="preco" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="imagem" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="id_fornecedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Fornecedores_Produtos" Member="Fornecedores" ThisKey="id_fornecedor" OtherKey="id" Type="Fornecedores" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipoUsuario" Member="TipoUsuario">
    <Type Name="TipoUsuario">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="TipoUsuario_Usuarios" Member="Usuarios" ThisKey="id" OtherKey="id_tipo_pessoa" Type="Usuarios" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="data_nascimento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="complemento" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="numero_casa" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="telefone" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="id_pessoa_fisica" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_tipo_pessoa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_endereco" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Enderecos_Usuarios" Member="Enderecos" ThisKey="id_endereco" OtherKey="id" Type="Enderecos" IsForeignKey="true" />
      <Association Name="PessoaFisica_Usuarios" Member="PessoaFisica" ThisKey="id_pessoa_fisica" OtherKey="id" Type="PessoaFisica" IsForeignKey="true" />
      <Association Name="TipoUsuario_Usuarios" Member="TipoUsuario" ThisKey="id_tipo_pessoa" OtherKey="id" Type="TipoUsuario" IsForeignKey="true" />
    </Type>
  </Table>
</Database>