#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPowerLook.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PowerLook")]
	public partial class PowerLookDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFornecedores(Fornecedores instance);
    partial void UpdateFornecedores(Fornecedores instance);
    partial void DeleteFornecedores(Fornecedores instance);
    partial void InsertPessoaFisica(PessoaFisica instance);
    partial void UpdatePessoaFisica(PessoaFisica instance);
    partial void DeletePessoaFisica(PessoaFisica instance);
    partial void InsertEnderecos(Enderecos instance);
    partial void UpdateEnderecos(Enderecos instance);
    partial void DeleteEnderecos(Enderecos instance);
    partial void InsertPessoaJurifica(PessoaJurifica instance);
    partial void UpdatePessoaJurifica(PessoaJurifica instance);
    partial void DeletePessoaJurifica(PessoaJurifica instance);
    partial void InsertTipoUsuario(TipoUsuario instance);
    partial void UpdateTipoUsuario(TipoUsuario instance);
    partial void DeleteTipoUsuario(TipoUsuario instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertCategorias(Categorias instance);
    partial void UpdateCategorias(Categorias instance);
    partial void DeleteCategorias(Categorias instance);
    partial void InsertProdutos(Produtos instance);
    partial void UpdateProdutos(Produtos instance);
    partial void DeleteProdutos(Produtos instance);
    partial void InsertVenda(Venda instance);
    partial void UpdateVenda(Venda instance);
    partial void DeleteVenda(Venda instance);
    partial void InsertitensVenda(itensVenda instance);
    partial void UpdateitensVenda(itensVenda instance);
    partial void DeleteitensVenda(itensVenda instance);
    partial void InsertContasReceber(ContasReceber instance);
    partial void UpdateContasReceber(ContasReceber instance);
    partial void DeleteContasReceber(ContasReceber instance);
    partial void InsertStatusPagamento(StatusPagamento instance);
    partial void UpdateStatusPagamento(StatusPagamento instance);
    partial void DeleteStatusPagamento(StatusPagamento instance);
    partial void InsertLogin(Login instance);
    partial void UpdateLogin(Login instance);
    partial void DeleteLogin(Login instance);
    #endregion
		
		public PowerLookDataContext() : 
				base(global::DBPowerLook.DAL.Properties.Settings.Default.PowerLookConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PowerLookDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PowerLookDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PowerLookDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PowerLookDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Fornecedores> Fornecedores
		{
			get
			{
				return this.GetTable<Fornecedores>();
			}
		}
		
		public System.Data.Linq.Table<PessoaFisica> PessoaFisica
		{
			get
			{
				return this.GetTable<PessoaFisica>();
			}
		}
		
		public System.Data.Linq.Table<Enderecos> Enderecos
		{
			get
			{
				return this.GetTable<Enderecos>();
			}
		}
		
		public System.Data.Linq.Table<PessoaJurifica> PessoaJurifica
		{
			get
			{
				return this.GetTable<PessoaJurifica>();
			}
		}
		
		public System.Data.Linq.Table<TipoUsuario> TipoUsuario
		{
			get
			{
				return this.GetTable<TipoUsuario>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Categorias> Categorias
		{
			get
			{
				return this.GetTable<Categorias>();
			}
		}
		
		public System.Data.Linq.Table<Produtos> Produtos
		{
			get
			{
				return this.GetTable<Produtos>();
			}
		}
		
		public System.Data.Linq.Table<Venda> Venda
		{
			get
			{
				return this.GetTable<Venda>();
			}
		}
		
		public System.Data.Linq.Table<itensVenda> itensVenda
		{
			get
			{
				return this.GetTable<itensVenda>();
			}
		}
		
		public System.Data.Linq.Table<ContasReceber> ContasReceber
		{
			get
			{
				return this.GetTable<ContasReceber>();
			}
		}
		
		public System.Data.Linq.Table<StatusPagamento> StatusPagamento
		{
			get
			{
				return this.GetTable<StatusPagamento>();
			}
		}
		
		public System.Data.Linq.Table<Login> Login
		{
			get
			{
				return this.GetTable<Login>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fornecedores")]
	public partial class Fornecedores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome_fantasia;
		
		private string _email;
		
		private string _telefone;
		
		private System.Nullable<int> _id_pessoa_juridica;
		
		private string _complemento;
		
		private string _numero_casa;
		
		private int _id_endereco;
		
		private EntitySet<Produtos> _Produtos;
		
		private EntityRef<Enderecos> _Enderecos;
		
		private EntityRef<PessoaJurifica> _PessoaJurifica;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnome_fantasiaChanging(string value);
    partial void Onnome_fantasiaChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void Onid_pessoa_juridicaChanging(System.Nullable<int> value);
    partial void Onid_pessoa_juridicaChanged();
    partial void OncomplementoChanging(string value);
    partial void OncomplementoChanged();
    partial void Onnumero_casaChanging(string value);
    partial void Onnumero_casaChanged();
    partial void Onid_enderecoChanging(int value);
    partial void Onid_enderecoChanged();
    #endregion
		
		public Fornecedores()
		{
			this._Produtos = new EntitySet<Produtos>(new Action<Produtos>(this.attach_Produtos), new Action<Produtos>(this.detach_Produtos));
			this._Enderecos = default(EntityRef<Enderecos>);
			this._PessoaJurifica = default(EntityRef<PessoaJurifica>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_fantasia", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nome_fantasia
		{
			get
			{
				return this._nome_fantasia;
			}
			set
			{
				if ((this._nome_fantasia != value))
				{
					this.Onnome_fantasiaChanging(value);
					this.SendPropertyChanging();
					this._nome_fantasia = value;
					this.SendPropertyChanged("nome_fantasia");
					this.Onnome_fantasiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa_juridica", DbType="Int")]
		public System.Nullable<int> id_pessoa_juridica
		{
			get
			{
				return this._id_pessoa_juridica;
			}
			set
			{
				if ((this._id_pessoa_juridica != value))
				{
					if (this._PessoaJurifica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pessoa_juridicaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa_juridica = value;
					this.SendPropertyChanged("id_pessoa_juridica");
					this.Onid_pessoa_juridicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this.OncomplementoChanging(value);
					this.SendPropertyChanging();
					this._complemento = value;
					this.SendPropertyChanged("complemento");
					this.OncomplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_casa", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string numero_casa
		{
			get
			{
				return this._numero_casa;
			}
			set
			{
				if ((this._numero_casa != value))
				{
					this.Onnumero_casaChanging(value);
					this.SendPropertyChanging();
					this._numero_casa = value;
					this.SendPropertyChanged("numero_casa");
					this.Onnumero_casaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_endereco", DbType="Int NOT NULL")]
		public int id_endereco
		{
			get
			{
				return this._id_endereco;
			}
			set
			{
				if ((this._id_endereco != value))
				{
					if (this._Enderecos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_enderecoChanging(value);
					this.SendPropertyChanging();
					this._id_endereco = value;
					this.SendPropertyChanged("id_endereco");
					this.Onid_enderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fornecedores_Produtos", Storage="_Produtos", ThisKey="id", OtherKey="id_fornecedor")]
		public EntitySet<Produtos> Produtos
		{
			get
			{
				return this._Produtos;
			}
			set
			{
				this._Produtos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enderecos_Fornecedores", Storage="_Enderecos", ThisKey="id_endereco", OtherKey="id", IsForeignKey=true)]
		public Enderecos Enderecos
		{
			get
			{
				return this._Enderecos.Entity;
			}
			set
			{
				Enderecos previousValue = this._Enderecos.Entity;
				if (((previousValue != value) 
							|| (this._Enderecos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Enderecos.Entity = null;
						previousValue.Fornecedores.Remove(this);
					}
					this._Enderecos.Entity = value;
					if ((value != null))
					{
						value.Fornecedores.Add(this);
						this._id_endereco = value.id;
					}
					else
					{
						this._id_endereco = default(int);
					}
					this.SendPropertyChanged("Enderecos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PessoaJurifica_Fornecedores", Storage="_PessoaJurifica", ThisKey="id_pessoa_juridica", OtherKey="id", IsForeignKey=true)]
		public PessoaJurifica PessoaJurifica
		{
			get
			{
				return this._PessoaJurifica.Entity;
			}
			set
			{
				PessoaJurifica previousValue = this._PessoaJurifica.Entity;
				if (((previousValue != value) 
							|| (this._PessoaJurifica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PessoaJurifica.Entity = null;
						previousValue.Fornecedores.Remove(this);
					}
					this._PessoaJurifica.Entity = value;
					if ((value != null))
					{
						value.Fornecedores.Add(this);
						this._id_pessoa_juridica = value.id;
					}
					else
					{
						this._id_pessoa_juridica = default(Nullable<int>);
					}
					this.SendPropertyChanged("PessoaJurifica");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Produtos(Produtos entity)
		{
			this.SendPropertyChanging();
			entity.Fornecedores = this;
		}
		
		private void detach_Produtos(Produtos entity)
		{
			this.SendPropertyChanging();
			entity.Fornecedores = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PessoaFisica")]
	public partial class PessoaFisica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _cpf;
		
		private string _rg;
		
		private EntitySet<Usuarios> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncpfChanging(string value);
    partial void OncpfChanged();
    partial void OnrgChanging(string value);
    partial void OnrgChanged();
    #endregion
		
		public PessoaFisica()
		{
			this._Usuarios = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios), new Action<Usuarios>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string cpf
		{
			get
			{
				return this._cpf;
			}
			set
			{
				if ((this._cpf != value))
				{
					this.OncpfChanging(value);
					this.SendPropertyChanging();
					this._cpf = value;
					this.SendPropertyChanged("cpf");
					this.OncpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rg", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string rg
		{
			get
			{
				return this._rg;
			}
			set
			{
				if ((this._rg != value))
				{
					this.OnrgChanging(value);
					this.SendPropertyChanging();
					this._rg = value;
					this.SendPropertyChanged("rg");
					this.OnrgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PessoaFisica_Usuarios", Storage="_Usuarios", ThisKey="id", OtherKey="id_pessoa_fisica")]
		public EntitySet<Usuarios> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.PessoaFisica = this;
		}
		
		private void detach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.PessoaFisica = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Enderecos")]
	public partial class Enderecos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _cep;
		
		private string _endereco;
		
		private string _bairro;
		
		private string _cidade;
		
		private string _estado;
		
		private string _uf;
		
		private EntitySet<Fornecedores> _Fornecedores;
		
		private EntitySet<Usuarios> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void OnenderecoChanging(string value);
    partial void OnenderecoChanged();
    partial void OnbairroChanging(string value);
    partial void OnbairroChanged();
    partial void OncidadeChanging(string value);
    partial void OncidadeChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnufChanging(string value);
    partial void OnufChanged();
    #endregion
		
		public Enderecos()
		{
			this._Fornecedores = new EntitySet<Fornecedores>(new Action<Fornecedores>(this.attach_Fornecedores), new Action<Fornecedores>(this.detach_Fornecedores));
			this._Usuarios = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios), new Action<Usuarios>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string endereco
		{
			get
			{
				return this._endereco;
			}
			set
			{
				if ((this._endereco != value))
				{
					this.OnenderecoChanging(value);
					this.SendPropertyChanging();
					this._endereco = value;
					this.SendPropertyChanged("endereco");
					this.OnenderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				if ((this._bairro != value))
				{
					this.OnbairroChanging(value);
					this.SendPropertyChanging();
					this._bairro = value;
					this.SendPropertyChanged("bairro");
					this.OnbairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uf", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string uf
		{
			get
			{
				return this._uf;
			}
			set
			{
				if ((this._uf != value))
				{
					this.OnufChanging(value);
					this.SendPropertyChanging();
					this._uf = value;
					this.SendPropertyChanged("uf");
					this.OnufChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enderecos_Fornecedores", Storage="_Fornecedores", ThisKey="id", OtherKey="id_endereco")]
		public EntitySet<Fornecedores> Fornecedores
		{
			get
			{
				return this._Fornecedores;
			}
			set
			{
				this._Fornecedores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enderecos_Usuarios", Storage="_Usuarios", ThisKey="id", OtherKey="id_endereco")]
		public EntitySet<Usuarios> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fornecedores(Fornecedores entity)
		{
			this.SendPropertyChanging();
			entity.Enderecos = this;
		}
		
		private void detach_Fornecedores(Fornecedores entity)
		{
			this.SendPropertyChanging();
			entity.Enderecos = null;
		}
		
		private void attach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Enderecos = this;
		}
		
		private void detach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Enderecos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PessoaJurifica")]
	public partial class PessoaJurifica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _cnpj;
		
		private string _inscricao_estadual;
		
		private string _razao_social;
		
		private EntitySet<Fornecedores> _Fornecedores;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncnpjChanging(string value);
    partial void OncnpjChanged();
    partial void Oninscricao_estadualChanging(string value);
    partial void Oninscricao_estadualChanged();
    partial void Onrazao_socialChanging(string value);
    partial void Onrazao_socialChanged();
    #endregion
		
		public PessoaJurifica()
		{
			this._Fornecedores = new EntitySet<Fornecedores>(new Action<Fornecedores>(this.attach_Fornecedores), new Action<Fornecedores>(this.detach_Fornecedores));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnpj", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string cnpj
		{
			get
			{
				return this._cnpj;
			}
			set
			{
				if ((this._cnpj != value))
				{
					this.OncnpjChanging(value);
					this.SendPropertyChanging();
					this._cnpj = value;
					this.SendPropertyChanged("cnpj");
					this.OncnpjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inscricao_estadual", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string inscricao_estadual
		{
			get
			{
				return this._inscricao_estadual;
			}
			set
			{
				if ((this._inscricao_estadual != value))
				{
					this.Oninscricao_estadualChanging(value);
					this.SendPropertyChanging();
					this._inscricao_estadual = value;
					this.SendPropertyChanged("inscricao_estadual");
					this.Oninscricao_estadualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_razao_social", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string razao_social
		{
			get
			{
				return this._razao_social;
			}
			set
			{
				if ((this._razao_social != value))
				{
					this.Onrazao_socialChanging(value);
					this.SendPropertyChanging();
					this._razao_social = value;
					this.SendPropertyChanged("razao_social");
					this.Onrazao_socialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PessoaJurifica_Fornecedores", Storage="_Fornecedores", ThisKey="id", OtherKey="id_pessoa_juridica")]
		public EntitySet<Fornecedores> Fornecedores
		{
			get
			{
				return this._Fornecedores;
			}
			set
			{
				this._Fornecedores.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fornecedores(Fornecedores entity)
		{
			this.SendPropertyChanging();
			entity.PessoaJurifica = this;
		}
		
		private void detach_Fornecedores(Fornecedores entity)
		{
			this.SendPropertyChanging();
			entity.PessoaJurifica = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoUsuario")]
	public partial class TipoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<Usuarios> _Usuarios;
		
		private EntitySet<Login> _Login;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public TipoUsuario()
		{
			this._Usuarios = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios), new Action<Usuarios>(this.detach_Usuarios));
			this._Login = new EntitySet<Login>(new Action<Login>(this.attach_Login), new Action<Login>(this.detach_Login));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_Usuarios", Storage="_Usuarios", ThisKey="id", OtherKey="id_tipo_pessoa")]
		public EntitySet<Usuarios> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_Login", Storage="_Login", ThisKey="id", OtherKey="id_tipoLogin")]
		public EntitySet<Login> Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				this._Login.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = this;
		}
		
		private void detach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = null;
		}
		
		private void attach_Login(Login entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = this;
		}
		
		private void detach_Login(Login entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private string _email;
		
		private System.DateTime _data_nascimento;
		
		private string _complemento;
		
		private string _numero_casa;
		
		private string _telefone;
		
		private System.Nullable<int> _id_pessoa_fisica;
		
		private int _id_tipo_pessoa;
		
		private int _id_endereco;
		
		private EntitySet<Venda> _Venda;
		
		private EntityRef<Enderecos> _Enderecos;
		
		private EntityRef<PessoaFisica> _PessoaFisica;
		
		private EntityRef<TipoUsuario> _TipoUsuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ondata_nascimentoChanging(System.DateTime value);
    partial void Ondata_nascimentoChanged();
    partial void OncomplementoChanging(string value);
    partial void OncomplementoChanged();
    partial void Onnumero_casaChanging(string value);
    partial void Onnumero_casaChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void Onid_pessoa_fisicaChanging(System.Nullable<int> value);
    partial void Onid_pessoa_fisicaChanged();
    partial void Onid_tipo_pessoaChanging(int value);
    partial void Onid_tipo_pessoaChanged();
    partial void Onid_enderecoChanging(int value);
    partial void Onid_enderecoChanged();
    #endregion
		
		public Usuarios()
		{
			this._Venda = new EntitySet<Venda>(new Action<Venda>(this.attach_Venda), new Action<Venda>(this.detach_Venda));
			this._Enderecos = default(EntityRef<Enderecos>);
			this._PessoaFisica = default(EntityRef<PessoaFisica>);
			this._TipoUsuario = default(EntityRef<TipoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_nascimento", DbType="Date NOT NULL")]
		public System.DateTime data_nascimento
		{
			get
			{
				return this._data_nascimento;
			}
			set
			{
				if ((this._data_nascimento != value))
				{
					this.Ondata_nascimentoChanging(value);
					this.SendPropertyChanging();
					this._data_nascimento = value;
					this.SendPropertyChanged("data_nascimento");
					this.Ondata_nascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this.OncomplementoChanging(value);
					this.SendPropertyChanging();
					this._complemento = value;
					this.SendPropertyChanged("complemento");
					this.OncomplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_casa", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string numero_casa
		{
			get
			{
				return this._numero_casa;
			}
			set
			{
				if ((this._numero_casa != value))
				{
					this.Onnumero_casaChanging(value);
					this.SendPropertyChanging();
					this._numero_casa = value;
					this.SendPropertyChanged("numero_casa");
					this.Onnumero_casaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa_fisica", DbType="Int")]
		public System.Nullable<int> id_pessoa_fisica
		{
			get
			{
				return this._id_pessoa_fisica;
			}
			set
			{
				if ((this._id_pessoa_fisica != value))
				{
					if (this._PessoaFisica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pessoa_fisicaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa_fisica = value;
					this.SendPropertyChanged("id_pessoa_fisica");
					this.Onid_pessoa_fisicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_pessoa", DbType="Int NOT NULL")]
		public int id_tipo_pessoa
		{
			get
			{
				return this._id_tipo_pessoa;
			}
			set
			{
				if ((this._id_tipo_pessoa != value))
				{
					if (this._TipoUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tipo_pessoaChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_pessoa = value;
					this.SendPropertyChanged("id_tipo_pessoa");
					this.Onid_tipo_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_endereco", DbType="Int NOT NULL")]
		public int id_endereco
		{
			get
			{
				return this._id_endereco;
			}
			set
			{
				if ((this._id_endereco != value))
				{
					if (this._Enderecos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_enderecoChanging(value);
					this.SendPropertyChanging();
					this._id_endereco = value;
					this.SendPropertyChanged("id_endereco");
					this.Onid_enderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Venda", Storage="_Venda", ThisKey="id", OtherKey="id_usuario")]
		public EntitySet<Venda> Venda
		{
			get
			{
				return this._Venda;
			}
			set
			{
				this._Venda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enderecos_Usuarios", Storage="_Enderecos", ThisKey="id_endereco", OtherKey="id", IsForeignKey=true)]
		public Enderecos Enderecos
		{
			get
			{
				return this._Enderecos.Entity;
			}
			set
			{
				Enderecos previousValue = this._Enderecos.Entity;
				if (((previousValue != value) 
							|| (this._Enderecos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Enderecos.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Enderecos.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._id_endereco = value.id;
					}
					else
					{
						this._id_endereco = default(int);
					}
					this.SendPropertyChanged("Enderecos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PessoaFisica_Usuarios", Storage="_PessoaFisica", ThisKey="id_pessoa_fisica", OtherKey="id", IsForeignKey=true)]
		public PessoaFisica PessoaFisica
		{
			get
			{
				return this._PessoaFisica.Entity;
			}
			set
			{
				PessoaFisica previousValue = this._PessoaFisica.Entity;
				if (((previousValue != value) 
							|| (this._PessoaFisica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PessoaFisica.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._PessoaFisica.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._id_pessoa_fisica = value.id;
					}
					else
					{
						this._id_pessoa_fisica = default(Nullable<int>);
					}
					this.SendPropertyChanged("PessoaFisica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_Usuarios", Storage="_TipoUsuario", ThisKey="id_tipo_pessoa", OtherKey="id", IsForeignKey=true)]
		public TipoUsuario TipoUsuario
		{
			get
			{
				return this._TipoUsuario.Entity;
			}
			set
			{
				TipoUsuario previousValue = this._TipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoUsuario.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._TipoUsuario.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._id_tipo_pessoa = value.id;
					}
					else
					{
						this._id_tipo_pessoa = default(int);
					}
					this.SendPropertyChanged("TipoUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Venda(Venda entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Venda(Venda entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorias")]
	public partial class Categorias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private string _descrição;
		
		private EntitySet<Produtos> _Produtos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndescriçãoChanging(string value);
    partial void OndescriçãoChanged();
    #endregion
		
		public Categorias()
		{
			this._Produtos = new EntitySet<Produtos>(new Action<Produtos>(this.attach_Produtos), new Action<Produtos>(this.detach_Produtos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrição", DbType="NVarChar(50)")]
		public string descrição
		{
			get
			{
				return this._descrição;
			}
			set
			{
				if ((this._descrição != value))
				{
					this.OndescriçãoChanging(value);
					this.SendPropertyChanging();
					this._descrição = value;
					this.SendPropertyChanged("descrição");
					this.OndescriçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorias_Produtos", Storage="_Produtos", ThisKey="id", OtherKey="id_categoria")]
		public EntitySet<Produtos> Produtos
		{
			get
			{
				return this._Produtos;
			}
			set
			{
				this._Produtos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Produtos(Produtos entity)
		{
			this.SendPropertyChanging();
			entity.Categorias = this;
		}
		
		private void detach_Produtos(Produtos entity)
		{
			this.SendPropertyChanging();
			entity.Categorias = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produtos")]
	public partial class Produtos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private string _descricao;
		
		private string _tamanho;
		
		private string _tipo_manga;
		
		private string _tipo_decote;
		
		private string _cor;
		
		private decimal _preco;
		
		private int _id_fornecedor;
		
		private int _id_categoria;
		
		private int _quantidade;
		
		private EntitySet<itensVenda> _itensVenda;
		
		private EntityRef<Fornecedores> _Fornecedores;
		
		private EntityRef<Categorias> _Categorias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    partial void OntamanhoChanging(string value);
    partial void OntamanhoChanged();
    partial void Ontipo_mangaChanging(string value);
    partial void Ontipo_mangaChanged();
    partial void Ontipo_decoteChanging(string value);
    partial void Ontipo_decoteChanged();
    partial void OncorChanging(string value);
    partial void OncorChanged();
    partial void OnprecoChanging(decimal value);
    partial void OnprecoChanged();
    partial void Onid_fornecedorChanging(int value);
    partial void Onid_fornecedorChanged();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void OnquantidadeChanging(int value);
    partial void OnquantidadeChanged();
    #endregion
		
		public Produtos()
		{
			this._itensVenda = new EntitySet<itensVenda>(new Action<itensVenda>(this.attach_itensVenda), new Action<itensVenda>(this.detach_itensVenda));
			this._Fornecedores = default(EntityRef<Fornecedores>);
			this._Categorias = default(EntityRef<Categorias>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="NVarChar(255)")]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamanho", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string tamanho
		{
			get
			{
				return this._tamanho;
			}
			set
			{
				if ((this._tamanho != value))
				{
					this.OntamanhoChanging(value);
					this.SendPropertyChanging();
					this._tamanho = value;
					this.SendPropertyChanged("tamanho");
					this.OntamanhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_manga", DbType="NVarChar(255)")]
		public string tipo_manga
		{
			get
			{
				return this._tipo_manga;
			}
			set
			{
				if ((this._tipo_manga != value))
				{
					this.Ontipo_mangaChanging(value);
					this.SendPropertyChanging();
					this._tipo_manga = value;
					this.SendPropertyChanged("tipo_manga");
					this.Ontipo_mangaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_decote", DbType="NVarChar(255)")]
		public string tipo_decote
		{
			get
			{
				return this._tipo_decote;
			}
			set
			{
				if ((this._tipo_decote != value))
				{
					this.Ontipo_decoteChanging(value);
					this.SendPropertyChanging();
					this._tipo_decote = value;
					this.SendPropertyChanged("tipo_decote");
					this.Ontipo_decoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cor", DbType="NVarChar(255)")]
		public string cor
		{
			get
			{
				return this._cor;
			}
			set
			{
				if ((this._cor != value))
				{
					this.OncorChanging(value);
					this.SendPropertyChanging();
					this._cor = value;
					this.SendPropertyChanged("cor");
					this.OncorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preco", DbType="Decimal(18,2) NOT NULL")]
		public decimal preco
		{
			get
			{
				return this._preco;
			}
			set
			{
				if ((this._preco != value))
				{
					this.OnprecoChanging(value);
					this.SendPropertyChanging();
					this._preco = value;
					this.SendPropertyChanged("preco");
					this.OnprecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fornecedor", DbType="Int NOT NULL")]
		public int id_fornecedor
		{
			get
			{
				return this._id_fornecedor;
			}
			set
			{
				if ((this._id_fornecedor != value))
				{
					if (this._Fornecedores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fornecedorChanging(value);
					this.SendPropertyChanging();
					this._id_fornecedor = value;
					this.SendPropertyChanged("id_fornecedor");
					this.Onid_fornecedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int NOT NULL")]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._Categorias.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantidade")]
		public int quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				if ((this._quantidade != value))
				{
					this.OnquantidadeChanging(value);
					this.SendPropertyChanging();
					this._quantidade = value;
					this.SendPropertyChanged("quantidade");
					this.OnquantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produtos_itensVenda", Storage="_itensVenda", ThisKey="id", OtherKey="id_produto")]
		public EntitySet<itensVenda> itensVenda
		{
			get
			{
				return this._itensVenda;
			}
			set
			{
				this._itensVenda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fornecedores_Produtos", Storage="_Fornecedores", ThisKey="id_fornecedor", OtherKey="id", IsForeignKey=true)]
		public Fornecedores Fornecedores
		{
			get
			{
				return this._Fornecedores.Entity;
			}
			set
			{
				Fornecedores previousValue = this._Fornecedores.Entity;
				if (((previousValue != value) 
							|| (this._Fornecedores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Fornecedores.Entity = null;
						previousValue.Produtos.Remove(this);
					}
					this._Fornecedores.Entity = value;
					if ((value != null))
					{
						value.Produtos.Add(this);
						this._id_fornecedor = value.id;
					}
					else
					{
						this._id_fornecedor = default(int);
					}
					this.SendPropertyChanged("Fornecedores");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorias_Produtos", Storage="_Categorias", ThisKey="id_categoria", OtherKey="id", IsForeignKey=true)]
		public Categorias Categorias
		{
			get
			{
				return this._Categorias.Entity;
			}
			set
			{
				Categorias previousValue = this._Categorias.Entity;
				if (((previousValue != value) 
							|| (this._Categorias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categorias.Entity = null;
						previousValue.Produtos.Remove(this);
					}
					this._Categorias.Entity = value;
					if ((value != null))
					{
						value.Produtos.Add(this);
						this._id_categoria = value.id;
					}
					else
					{
						this._id_categoria = default(int);
					}
					this.SendPropertyChanged("Categorias");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_itensVenda(itensVenda entity)
		{
			this.SendPropertyChanging();
			entity.Produtos = this;
		}
		
		private void detach_itensVenda(itensVenda entity)
		{
			this.SendPropertyChanging();
			entity.Produtos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Venda")]
	public partial class Venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_venda;
		
		private System.Nullable<decimal> _valor;
		
		private System.Nullable<decimal> _desconto;
		
		private System.Nullable<decimal> _valor_pago;
		
		private int _id_usuario;
		
		private EntitySet<itensVenda> _itensVenda;
		
		private EntitySet<ContasReceber> _ContasReceber;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vendaChanging(int value);
    partial void Onid_vendaChanged();
    partial void OnvalorChanging(System.Nullable<decimal> value);
    partial void OnvalorChanged();
    partial void OndescontoChanging(System.Nullable<decimal> value);
    partial void OndescontoChanged();
    partial void Onvalor_pagoChanging(System.Nullable<decimal> value);
    partial void Onvalor_pagoChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    #endregion
		
		public Venda()
		{
			this._itensVenda = new EntitySet<itensVenda>(new Action<itensVenda>(this.attach_itensVenda), new Action<itensVenda>(this.detach_itensVenda));
			this._ContasReceber = new EntitySet<ContasReceber>(new Action<ContasReceber>(this.attach_ContasReceber), new Action<ContasReceber>(this.detach_ContasReceber));
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desconto", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> desconto
		{
			get
			{
				return this._desconto;
			}
			set
			{
				if ((this._desconto != value))
				{
					this.OndescontoChanging(value);
					this.SendPropertyChanging();
					this._desconto = value;
					this.SendPropertyChanged("desconto");
					this.OndescontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_pago", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> valor_pago
		{
			get
			{
				return this._valor_pago;
			}
			set
			{
				if ((this._valor_pago != value))
				{
					this.Onvalor_pagoChanging(value);
					this.SendPropertyChanging();
					this._valor_pago = value;
					this.SendPropertyChanged("valor_pago");
					this.Onvalor_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_itensVenda", Storage="_itensVenda", ThisKey="id_venda", OtherKey="id_venda")]
		public EntitySet<itensVenda> itensVenda
		{
			get
			{
				return this._itensVenda;
			}
			set
			{
				this._itensVenda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_ContasReceber", Storage="_ContasReceber", ThisKey="id_venda", OtherKey="id_venda")]
		public EntitySet<ContasReceber> ContasReceber
		{
			get
			{
				return this._ContasReceber;
			}
			set
			{
				this._ContasReceber.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Venda", Storage="_Usuarios", ThisKey="id_usuario", OtherKey="id", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Venda.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Venda.Add(this);
						this._id_usuario = value.id;
					}
					else
					{
						this._id_usuario = default(int);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_itensVenda(itensVenda entity)
		{
			this.SendPropertyChanging();
			entity.Venda = this;
		}
		
		private void detach_itensVenda(itensVenda entity)
		{
			this.SendPropertyChanging();
			entity.Venda = null;
		}
		
		private void attach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.Venda = this;
		}
		
		private void detach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.Venda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.itensVenda")]
	public partial class itensVenda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_item;
		
		private int _id_produto;
		
		private int _id_venda;
		
		private int _quantidade;
		
		private decimal _valor;
		
		private EntityRef<Produtos> _Produtos;
		
		private EntityRef<Venda> _Venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_itemChanging(int value);
    partial void Onid_itemChanged();
    partial void Onid_produtoChanging(int value);
    partial void Onid_produtoChanged();
    partial void Onid_vendaChanging(int value);
    partial void Onid_vendaChanged();
    partial void OnquantidadeChanging(int value);
    partial void OnquantidadeChanged();
    partial void OnvalorChanging(decimal value);
    partial void OnvalorChanged();
    #endregion
		
		public itensVenda()
		{
			this._Produtos = default(EntityRef<Produtos>);
			this._Venda = default(EntityRef<Venda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_item", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_item
		{
			get
			{
				return this._id_item;
			}
			set
			{
				if ((this._id_item != value))
				{
					this.Onid_itemChanging(value);
					this.SendPropertyChanging();
					this._id_item = value;
					this.SendPropertyChanged("id_item");
					this.Onid_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", DbType="Int NOT NULL")]
		public int id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					if (this._Produtos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", DbType="Int NOT NULL")]
		public int id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					if (this._Venda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantidade", DbType="Int NOT NULL")]
		public int quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				if ((this._quantidade != value))
				{
					this.OnquantidadeChanging(value);
					this.SendPropertyChanging();
					this._quantidade = value;
					this.SendPropertyChanged("quantidade");
					this.OnquantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(15,2) NOT NULL")]
		public decimal valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produtos_itensVenda", Storage="_Produtos", ThisKey="id_produto", OtherKey="id", IsForeignKey=true)]
		public Produtos Produtos
		{
			get
			{
				return this._Produtos.Entity;
			}
			set
			{
				Produtos previousValue = this._Produtos.Entity;
				if (((previousValue != value) 
							|| (this._Produtos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produtos.Entity = null;
						previousValue.itensVenda.Remove(this);
					}
					this._Produtos.Entity = value;
					if ((value != null))
					{
						value.itensVenda.Add(this);
						this._id_produto = value.id;
					}
					else
					{
						this._id_produto = default(int);
					}
					this.SendPropertyChanged("Produtos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_itensVenda", Storage="_Venda", ThisKey="id_venda", OtherKey="id_venda", IsForeignKey=true)]
		public Venda Venda
		{
			get
			{
				return this._Venda.Entity;
			}
			set
			{
				Venda previousValue = this._Venda.Entity;
				if (((previousValue != value) 
							|| (this._Venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Venda.Entity = null;
						previousValue.itensVenda.Remove(this);
					}
					this._Venda.Entity = value;
					if ((value != null))
					{
						value.itensVenda.Add(this);
						this._id_venda = value.id_venda;
					}
					else
					{
						this._id_venda = default(int);
					}
					this.SendPropertyChanged("Venda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ContasReceber")]
	public partial class ContasReceber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_conta;
		
		private System.DateTime _data_compra;
		
		private System.DateTime _data_vencimento;
		
		private System.Nullable<System.DateTime> _data_pagamento;
		
		private int _id_venda;
		
		private int _id_status;
		
		private EntityRef<Venda> _Venda;
		
		private EntityRef<StatusPagamento> _StatusPagamento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_contaChanging(int value);
    partial void Onid_contaChanged();
    partial void Ondata_compraChanging(System.DateTime value);
    partial void Ondata_compraChanged();
    partial void Ondata_vencimentoChanging(System.DateTime value);
    partial void Ondata_vencimentoChanged();
    partial void Ondata_pagamentoChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_pagamentoChanged();
    partial void Onid_vendaChanging(int value);
    partial void Onid_vendaChanged();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    #endregion
		
		public ContasReceber()
		{
			this._Venda = default(EntityRef<Venda>);
			this._StatusPagamento = default(EntityRef<StatusPagamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_conta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_conta
		{
			get
			{
				return this._id_conta;
			}
			set
			{
				if ((this._id_conta != value))
				{
					this.Onid_contaChanging(value);
					this.SendPropertyChanging();
					this._id_conta = value;
					this.SendPropertyChanged("id_conta");
					this.Onid_contaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_compra", DbType="Date NOT NULL")]
		public System.DateTime data_compra
		{
			get
			{
				return this._data_compra;
			}
			set
			{
				if ((this._data_compra != value))
				{
					this.Ondata_compraChanging(value);
					this.SendPropertyChanging();
					this._data_compra = value;
					this.SendPropertyChanged("data_compra");
					this.Ondata_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_vencimento", DbType="Date NOT NULL")]
		public System.DateTime data_vencimento
		{
			get
			{
				return this._data_vencimento;
			}
			set
			{
				if ((this._data_vencimento != value))
				{
					this.Ondata_vencimentoChanging(value);
					this.SendPropertyChanging();
					this._data_vencimento = value;
					this.SendPropertyChanged("data_vencimento");
					this.Ondata_vencimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_pagamento", DbType="Date")]
		public System.Nullable<System.DateTime> data_pagamento
		{
			get
			{
				return this._data_pagamento;
			}
			set
			{
				if ((this._data_pagamento != value))
				{
					this.Ondata_pagamentoChanging(value);
					this.SendPropertyChanging();
					this._data_pagamento = value;
					this.SendPropertyChanged("data_pagamento");
					this.Ondata_pagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", DbType="Int NOT NULL")]
		public int id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					if (this._Venda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", DbType="Int NOT NULL")]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					if (this._StatusPagamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_ContasReceber", Storage="_Venda", ThisKey="id_venda", OtherKey="id_venda", IsForeignKey=true)]
		public Venda Venda
		{
			get
			{
				return this._Venda.Entity;
			}
			set
			{
				Venda previousValue = this._Venda.Entity;
				if (((previousValue != value) 
							|| (this._Venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Venda.Entity = null;
						previousValue.ContasReceber.Remove(this);
					}
					this._Venda.Entity = value;
					if ((value != null))
					{
						value.ContasReceber.Add(this);
						this._id_venda = value.id_venda;
					}
					else
					{
						this._id_venda = default(int);
					}
					this.SendPropertyChanged("Venda");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StatusPagamento_ContasReceber", Storage="_StatusPagamento", ThisKey="id_status", OtherKey="id_status", IsForeignKey=true)]
		public StatusPagamento StatusPagamento
		{
			get
			{
				return this._StatusPagamento.Entity;
			}
			set
			{
				StatusPagamento previousValue = this._StatusPagamento.Entity;
				if (((previousValue != value) 
							|| (this._StatusPagamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StatusPagamento.Entity = null;
						previousValue.ContasReceber.Remove(this);
					}
					this._StatusPagamento.Entity = value;
					if ((value != null))
					{
						value.ContasReceber.Add(this);
						this._id_status = value.id_status;
					}
					else
					{
						this._id_status = default(int);
					}
					this.SendPropertyChanged("StatusPagamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StatusPagamento")]
	public partial class StatusPagamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_status;
		
		private string _status;
		
		private EntitySet<ContasReceber> _ContasReceber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public StatusPagamento()
		{
			this._ContasReceber = new EntitySet<ContasReceber>(new Action<ContasReceber>(this.attach_ContasReceber), new Action<ContasReceber>(this.detach_ContasReceber));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StatusPagamento_ContasReceber", Storage="_ContasReceber", ThisKey="id_status", OtherKey="id_status")]
		public EntitySet<ContasReceber> ContasReceber
		{
			get
			{
				return this._ContasReceber;
			}
			set
			{
				this._ContasReceber.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.StatusPagamento = this;
		}
		
		private void detach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.StatusPagamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Login")]
	public partial class Login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _login1;
		
		private string _senha;
		
		private System.Nullable<int> _id_tipoLogin;
		
		private EntityRef<TipoUsuario> _TipoUsuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onlogin1Changing(string value);
    partial void Onlogin1Changed();
    partial void OnsenhaChanging(string value);
    partial void OnsenhaChanged();
    partial void Onid_tipoLoginChanging(System.Nullable<int> value);
    partial void Onid_tipoLoginChanged();
    #endregion
		
		public Login()
		{
			this._TipoUsuario = default(EntityRef<TipoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="login", Storage="_login1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string login1
		{
			get
			{
				return this._login1;
			}
			set
			{
				if ((this._login1 != value))
				{
					this.Onlogin1Changing(value);
					this.SendPropertyChanging();
					this._login1 = value;
					this.SendPropertyChanged("login1");
					this.Onlogin1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				if ((this._senha != value))
				{
					this.OnsenhaChanging(value);
					this.SendPropertyChanging();
					this._senha = value;
					this.SendPropertyChanged("senha");
					this.OnsenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipoLogin", DbType="Int")]
		public System.Nullable<int> id_tipoLogin
		{
			get
			{
				return this._id_tipoLogin;
			}
			set
			{
				if ((this._id_tipoLogin != value))
				{
					if (this._TipoUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tipoLoginChanging(value);
					this.SendPropertyChanging();
					this._id_tipoLogin = value;
					this.SendPropertyChanged("id_tipoLogin");
					this.Onid_tipoLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_Login", Storage="_TipoUsuario", ThisKey="id_tipoLogin", OtherKey="id", IsForeignKey=true)]
		public TipoUsuario TipoUsuario
		{
			get
			{
				return this._TipoUsuario.Entity;
			}
			set
			{
				TipoUsuario previousValue = this._TipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoUsuario.Entity = null;
						previousValue.Login.Remove(this);
					}
					this._TipoUsuario.Entity = value;
					if ((value != null))
					{
						value.Login.Add(this);
						this._id_tipoLogin = value.id;
					}
					else
					{
						this._id_tipoLogin = default(Nullable<int>);
					}
					this.SendPropertyChanged("TipoUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
