#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPowerLook.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PowerLook")]
	public partial class PowerLookDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFornecedores(Fornecedores instance);
    partial void UpdateFornecedores(Fornecedores instance);
    partial void DeleteFornecedores(Fornecedores instance);
    partial void InsertLocacoes(Locacoes instance);
    partial void UpdateLocacoes(Locacoes instance);
    partial void DeleteLocacoes(Locacoes instance);
    partial void InsertPessoaFisica(PessoaFisica instance);
    partial void UpdatePessoaFisica(PessoaFisica instance);
    partial void DeletePessoaFisica(PessoaFisica instance);
    partial void InsertEnderecos(Enderecos instance);
    partial void UpdateEnderecos(Enderecos instance);
    partial void DeleteEnderecos(Enderecos instance);
    partial void InsertPessoaJurifica(PessoaJurifica instance);
    partial void UpdatePessoaJurifica(PessoaJurifica instance);
    partial void DeletePessoaJurifica(PessoaJurifica instance);
    partial void InsertProdutos(Produtos instance);
    partial void UpdateProdutos(Produtos instance);
    partial void DeleteProdutos(Produtos instance);
    partial void InsertTipoUsuario(TipoUsuario instance);
    partial void UpdateTipoUsuario(TipoUsuario instance);
    partial void DeleteTipoUsuario(TipoUsuario instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    #endregion
		
		public PowerLookDataContext() : 
				base(global::DBPowerLook.DAL.Properties.Settings.Default.PowerLookConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PowerLookDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PowerLookDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PowerLookDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PowerLookDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Fornecedores> Fornecedores
		{
			get
			{
				return this.GetTable<Fornecedores>();
			}
		}
		
		public System.Data.Linq.Table<Locacoes> Locacoes
		{
			get
			{
				return this.GetTable<Locacoes>();
			}
		}
		
		public System.Data.Linq.Table<PessoaFisica> PessoaFisica
		{
			get
			{
				return this.GetTable<PessoaFisica>();
			}
		}
		
		public System.Data.Linq.Table<Enderecos> Enderecos
		{
			get
			{
				return this.GetTable<Enderecos>();
			}
		}
		
		public System.Data.Linq.Table<PessoaJurifica> PessoaJurifica
		{
			get
			{
				return this.GetTable<PessoaJurifica>();
			}
		}
		
		public System.Data.Linq.Table<Produtos> Produtos
		{
			get
			{
				return this.GetTable<Produtos>();
			}
		}
		
		public System.Data.Linq.Table<TipoUsuario> TipoUsuario
		{
			get
			{
				return this.GetTable<TipoUsuario>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fornecedores")]
	public partial class Fornecedores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome_fantasia;
		
		private string _email;
		
		private string _telefone;
		
		private System.Nullable<int> _id_pessoa_juridica;
		
		private string _complemento;
		
		private string _numero_casa;
		
		private int _id_endereco;
		
		private EntitySet<Produtos> _Produtos;
		
		private EntityRef<Enderecos> _Enderecos;
		
		private EntityRef<PessoaJurifica> _PessoaJurifica;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnome_fantasiaChanging(string value);
    partial void Onnome_fantasiaChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void Onid_pessoa_juridicaChanging(System.Nullable<int> value);
    partial void Onid_pessoa_juridicaChanged();
    partial void OncomplementoChanging(string value);
    partial void OncomplementoChanged();
    partial void Onnumero_casaChanging(string value);
    partial void Onnumero_casaChanged();
    partial void Onid_enderecoChanging(int value);
    partial void Onid_enderecoChanged();
    #endregion
		
		public Fornecedores()
		{
			this._Produtos = new EntitySet<Produtos>(new Action<Produtos>(this.attach_Produtos), new Action<Produtos>(this.detach_Produtos));
			this._Enderecos = default(EntityRef<Enderecos>);
			this._PessoaJurifica = default(EntityRef<PessoaJurifica>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_fantasia", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nome_fantasia
		{
			get
			{
				return this._nome_fantasia;
			}
			set
			{
				if ((this._nome_fantasia != value))
				{
					this.Onnome_fantasiaChanging(value);
					this.SendPropertyChanging();
					this._nome_fantasia = value;
					this.SendPropertyChanged("nome_fantasia");
					this.Onnome_fantasiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa_juridica", DbType="Int")]
		public System.Nullable<int> id_pessoa_juridica
		{
			get
			{
				return this._id_pessoa_juridica;
			}
			set
			{
				if ((this._id_pessoa_juridica != value))
				{
					if (this._PessoaJurifica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pessoa_juridicaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa_juridica = value;
					this.SendPropertyChanged("id_pessoa_juridica");
					this.Onid_pessoa_juridicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this.OncomplementoChanging(value);
					this.SendPropertyChanging();
					this._complemento = value;
					this.SendPropertyChanged("complemento");
					this.OncomplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_casa", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string numero_casa
		{
			get
			{
				return this._numero_casa;
			}
			set
			{
				if ((this._numero_casa != value))
				{
					this.Onnumero_casaChanging(value);
					this.SendPropertyChanging();
					this._numero_casa = value;
					this.SendPropertyChanged("numero_casa");
					this.Onnumero_casaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_endereco", DbType="Int NOT NULL")]
		public int id_endereco
		{
			get
			{
				return this._id_endereco;
			}
			set
			{
				if ((this._id_endereco != value))
				{
					if (this._Enderecos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_enderecoChanging(value);
					this.SendPropertyChanging();
					this._id_endereco = value;
					this.SendPropertyChanged("id_endereco");
					this.Onid_enderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fornecedores_Produtos", Storage="_Produtos", ThisKey="id", OtherKey="id_fornecedor")]
		public EntitySet<Produtos> Produtos
		{
			get
			{
				return this._Produtos;
			}
			set
			{
				this._Produtos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enderecos_Fornecedores", Storage="_Enderecos", ThisKey="id_endereco", OtherKey="id", IsForeignKey=true)]
		public Enderecos Enderecos
		{
			get
			{
				return this._Enderecos.Entity;
			}
			set
			{
				Enderecos previousValue = this._Enderecos.Entity;
				if (((previousValue != value) 
							|| (this._Enderecos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Enderecos.Entity = null;
						previousValue.Fornecedores.Remove(this);
					}
					this._Enderecos.Entity = value;
					if ((value != null))
					{
						value.Fornecedores.Add(this);
						this._id_endereco = value.id;
					}
					else
					{
						this._id_endereco = default(int);
					}
					this.SendPropertyChanged("Enderecos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PessoaJurifica_Fornecedores", Storage="_PessoaJurifica", ThisKey="id_pessoa_juridica", OtherKey="id", IsForeignKey=true)]
		public PessoaJurifica PessoaJurifica
		{
			get
			{
				return this._PessoaJurifica.Entity;
			}
			set
			{
				PessoaJurifica previousValue = this._PessoaJurifica.Entity;
				if (((previousValue != value) 
							|| (this._PessoaJurifica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PessoaJurifica.Entity = null;
						previousValue.Fornecedores.Remove(this);
					}
					this._PessoaJurifica.Entity = value;
					if ((value != null))
					{
						value.Fornecedores.Add(this);
						this._id_pessoa_juridica = value.id;
					}
					else
					{
						this._id_pessoa_juridica = default(Nullable<int>);
					}
					this.SendPropertyChanged("PessoaJurifica");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Produtos(Produtos entity)
		{
			this.SendPropertyChanging();
			entity.Fornecedores = this;
		}
		
		private void detach_Produtos(Produtos entity)
		{
			this.SendPropertyChanging();
			entity.Fornecedores = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Locacoes")]
	public partial class Locacoes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public Locacoes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PessoaFisica")]
	public partial class PessoaFisica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _cpf;
		
		private string _rg;
		
		private EntitySet<Usuarios> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncpfChanging(string value);
    partial void OncpfChanged();
    partial void OnrgChanging(string value);
    partial void OnrgChanged();
    #endregion
		
		public PessoaFisica()
		{
			this._Usuarios = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios), new Action<Usuarios>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string cpf
		{
			get
			{
				return this._cpf;
			}
			set
			{
				if ((this._cpf != value))
				{
					this.OncpfChanging(value);
					this.SendPropertyChanging();
					this._cpf = value;
					this.SendPropertyChanged("cpf");
					this.OncpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rg", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string rg
		{
			get
			{
				return this._rg;
			}
			set
			{
				if ((this._rg != value))
				{
					this.OnrgChanging(value);
					this.SendPropertyChanging();
					this._rg = value;
					this.SendPropertyChanged("rg");
					this.OnrgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PessoaFisica_Usuarios", Storage="_Usuarios", ThisKey="id", OtherKey="id_pessoa_fisica")]
		public EntitySet<Usuarios> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.PessoaFisica = this;
		}
		
		private void detach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.PessoaFisica = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Enderecos")]
	public partial class Enderecos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _cep;
		
		private string _endereco;
		
		private string _bairro;
		
		private string _cidade;
		
		private string _estado;
		
		private string _uf;
		
		private EntitySet<Fornecedores> _Fornecedores;
		
		private EntitySet<Usuarios> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void OnenderecoChanging(string value);
    partial void OnenderecoChanged();
    partial void OnbairroChanging(string value);
    partial void OnbairroChanged();
    partial void OncidadeChanging(string value);
    partial void OncidadeChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnufChanging(string value);
    partial void OnufChanged();
    #endregion
		
		public Enderecos()
		{
			this._Fornecedores = new EntitySet<Fornecedores>(new Action<Fornecedores>(this.attach_Fornecedores), new Action<Fornecedores>(this.detach_Fornecedores));
			this._Usuarios = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios), new Action<Usuarios>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string endereco
		{
			get
			{
				return this._endereco;
			}
			set
			{
				if ((this._endereco != value))
				{
					this.OnenderecoChanging(value);
					this.SendPropertyChanging();
					this._endereco = value;
					this.SendPropertyChanged("endereco");
					this.OnenderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				if ((this._bairro != value))
				{
					this.OnbairroChanging(value);
					this.SendPropertyChanging();
					this._bairro = value;
					this.SendPropertyChanged("bairro");
					this.OnbairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uf", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string uf
		{
			get
			{
				return this._uf;
			}
			set
			{
				if ((this._uf != value))
				{
					this.OnufChanging(value);
					this.SendPropertyChanging();
					this._uf = value;
					this.SendPropertyChanged("uf");
					this.OnufChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enderecos_Fornecedores", Storage="_Fornecedores", ThisKey="id", OtherKey="id_endereco")]
		public EntitySet<Fornecedores> Fornecedores
		{
			get
			{
				return this._Fornecedores;
			}
			set
			{
				this._Fornecedores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enderecos_Usuarios", Storage="_Usuarios", ThisKey="id", OtherKey="id_endereco")]
		public EntitySet<Usuarios> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fornecedores(Fornecedores entity)
		{
			this.SendPropertyChanging();
			entity.Enderecos = this;
		}
		
		private void detach_Fornecedores(Fornecedores entity)
		{
			this.SendPropertyChanging();
			entity.Enderecos = null;
		}
		
		private void attach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Enderecos = this;
		}
		
		private void detach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Enderecos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PessoaJurifica")]
	public partial class PessoaJurifica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _cnpj;
		
		private string _inscricao_estadual;
		
		private string _razao_social;
		
		private EntitySet<Fornecedores> _Fornecedores;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncnpjChanging(string value);
    partial void OncnpjChanged();
    partial void Oninscricao_estadualChanging(string value);
    partial void Oninscricao_estadualChanged();
    partial void Onrazao_socialChanging(string value);
    partial void Onrazao_socialChanged();
    #endregion
		
		public PessoaJurifica()
		{
			this._Fornecedores = new EntitySet<Fornecedores>(new Action<Fornecedores>(this.attach_Fornecedores), new Action<Fornecedores>(this.detach_Fornecedores));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnpj", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string cnpj
		{
			get
			{
				return this._cnpj;
			}
			set
			{
				if ((this._cnpj != value))
				{
					this.OncnpjChanging(value);
					this.SendPropertyChanging();
					this._cnpj = value;
					this.SendPropertyChanged("cnpj");
					this.OncnpjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inscricao_estadual", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string inscricao_estadual
		{
			get
			{
				return this._inscricao_estadual;
			}
			set
			{
				if ((this._inscricao_estadual != value))
				{
					this.Oninscricao_estadualChanging(value);
					this.SendPropertyChanging();
					this._inscricao_estadual = value;
					this.SendPropertyChanged("inscricao_estadual");
					this.Oninscricao_estadualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_razao_social", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string razao_social
		{
			get
			{
				return this._razao_social;
			}
			set
			{
				if ((this._razao_social != value))
				{
					this.Onrazao_socialChanging(value);
					this.SendPropertyChanging();
					this._razao_social = value;
					this.SendPropertyChanged("razao_social");
					this.Onrazao_socialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PessoaJurifica_Fornecedores", Storage="_Fornecedores", ThisKey="id", OtherKey="id_pessoa_juridica")]
		public EntitySet<Fornecedores> Fornecedores
		{
			get
			{
				return this._Fornecedores;
			}
			set
			{
				this._Fornecedores.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fornecedores(Fornecedores entity)
		{
			this.SendPropertyChanging();
			entity.PessoaJurifica = this;
		}
		
		private void detach_Fornecedores(Fornecedores entity)
		{
			this.SendPropertyChanging();
			entity.PessoaJurifica = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produtos")]
	public partial class Produtos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private string _descricao;
		
		private string _tamanho;
		
		private string _tipo_manga;
		
		private string _tipo_decote;
		
		private string _cor;
		
		private decimal _preco;
		
		private System.Data.Linq.Binary _imagem;
		
		private int _id_fornecedor;
		
		private EntityRef<Fornecedores> _Fornecedores;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    partial void OntamanhoChanging(string value);
    partial void OntamanhoChanged();
    partial void Ontipo_mangaChanging(string value);
    partial void Ontipo_mangaChanged();
    partial void Ontipo_decoteChanging(string value);
    partial void Ontipo_decoteChanged();
    partial void OncorChanging(string value);
    partial void OncorChanged();
    partial void OnprecoChanging(decimal value);
    partial void OnprecoChanged();
    partial void OnimagemChanging(System.Data.Linq.Binary value);
    partial void OnimagemChanged();
    partial void Onid_fornecedorChanging(int value);
    partial void Onid_fornecedorChanged();
    #endregion
		
		public Produtos()
		{
			this._Fornecedores = default(EntityRef<Fornecedores>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="NVarChar(255)")]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamanho", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string tamanho
		{
			get
			{
				return this._tamanho;
			}
			set
			{
				if ((this._tamanho != value))
				{
					this.OntamanhoChanging(value);
					this.SendPropertyChanging();
					this._tamanho = value;
					this.SendPropertyChanged("tamanho");
					this.OntamanhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_manga", DbType="NVarChar(255)")]
		public string tipo_manga
		{
			get
			{
				return this._tipo_manga;
			}
			set
			{
				if ((this._tipo_manga != value))
				{
					this.Ontipo_mangaChanging(value);
					this.SendPropertyChanging();
					this._tipo_manga = value;
					this.SendPropertyChanged("tipo_manga");
					this.Ontipo_mangaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_decote", DbType="NVarChar(255)")]
		public string tipo_decote
		{
			get
			{
				return this._tipo_decote;
			}
			set
			{
				if ((this._tipo_decote != value))
				{
					this.Ontipo_decoteChanging(value);
					this.SendPropertyChanging();
					this._tipo_decote = value;
					this.SendPropertyChanged("tipo_decote");
					this.Ontipo_decoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cor", DbType="NVarChar(255)")]
		public string cor
		{
			get
			{
				return this._cor;
			}
			set
			{
				if ((this._cor != value))
				{
					this.OncorChanging(value);
					this.SendPropertyChanging();
					this._cor = value;
					this.SendPropertyChanged("cor");
					this.OncorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preco", DbType="Decimal(18,2) NOT NULL")]
		public decimal preco
		{
			get
			{
				return this._preco;
			}
			set
			{
				if ((this._preco != value))
				{
					this.OnprecoChanging(value);
					this.SendPropertyChanging();
					this._preco = value;
					this.SendPropertyChanged("preco");
					this.OnprecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagem", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imagem
		{
			get
			{
				return this._imagem;
			}
			set
			{
				if ((this._imagem != value))
				{
					this.OnimagemChanging(value);
					this.SendPropertyChanging();
					this._imagem = value;
					this.SendPropertyChanged("imagem");
					this.OnimagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fornecedor", DbType="Int NOT NULL")]
		public int id_fornecedor
		{
			get
			{
				return this._id_fornecedor;
			}
			set
			{
				if ((this._id_fornecedor != value))
				{
					if (this._Fornecedores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fornecedorChanging(value);
					this.SendPropertyChanging();
					this._id_fornecedor = value;
					this.SendPropertyChanged("id_fornecedor");
					this.Onid_fornecedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fornecedores_Produtos", Storage="_Fornecedores", ThisKey="id_fornecedor", OtherKey="id", IsForeignKey=true)]
		public Fornecedores Fornecedores
		{
			get
			{
				return this._Fornecedores.Entity;
			}
			set
			{
				Fornecedores previousValue = this._Fornecedores.Entity;
				if (((previousValue != value) 
							|| (this._Fornecedores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Fornecedores.Entity = null;
						previousValue.Produtos.Remove(this);
					}
					this._Fornecedores.Entity = value;
					if ((value != null))
					{
						value.Produtos.Add(this);
						this._id_fornecedor = value.id;
					}
					else
					{
						this._id_fornecedor = default(int);
					}
					this.SendPropertyChanged("Fornecedores");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoUsuario")]
	public partial class TipoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<Usuarios> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public TipoUsuario()
		{
			this._Usuarios = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios), new Action<Usuarios>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_Usuarios", Storage="_Usuarios", ThisKey="id", OtherKey="id_tipo_pessoa")]
		public EntitySet<Usuarios> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = this;
		}
		
		private void detach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private string _email;
		
		private System.DateTime _data_nascimento;
		
		private string _complemento;
		
		private string _numero_casa;
		
		private string _telefone;
		
		private System.Nullable<int> _id_pessoa_fisica;
		
		private int _id_tipo_pessoa;
		
		private int _id_endereco;
		
		private EntityRef<Enderecos> _Enderecos;
		
		private EntityRef<PessoaFisica> _PessoaFisica;
		
		private EntityRef<TipoUsuario> _TipoUsuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ondata_nascimentoChanging(System.DateTime value);
    partial void Ondata_nascimentoChanged();
    partial void OncomplementoChanging(string value);
    partial void OncomplementoChanged();
    partial void Onnumero_casaChanging(string value);
    partial void Onnumero_casaChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void Onid_pessoa_fisicaChanging(System.Nullable<int> value);
    partial void Onid_pessoa_fisicaChanged();
    partial void Onid_tipo_pessoaChanging(int value);
    partial void Onid_tipo_pessoaChanged();
    partial void Onid_enderecoChanging(int value);
    partial void Onid_enderecoChanged();
    #endregion
		
		public Usuarios()
		{
			this._Enderecos = default(EntityRef<Enderecos>);
			this._PessoaFisica = default(EntityRef<PessoaFisica>);
			this._TipoUsuario = default(EntityRef<TipoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_nascimento", DbType="Date NOT NULL")]
		public System.DateTime data_nascimento
		{
			get
			{
				return this._data_nascimento;
			}
			set
			{
				if ((this._data_nascimento != value))
				{
					this.Ondata_nascimentoChanging(value);
					this.SendPropertyChanging();
					this._data_nascimento = value;
					this.SendPropertyChanged("data_nascimento");
					this.Ondata_nascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this.OncomplementoChanging(value);
					this.SendPropertyChanging();
					this._complemento = value;
					this.SendPropertyChanged("complemento");
					this.OncomplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_casa", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string numero_casa
		{
			get
			{
				return this._numero_casa;
			}
			set
			{
				if ((this._numero_casa != value))
				{
					this.Onnumero_casaChanging(value);
					this.SendPropertyChanging();
					this._numero_casa = value;
					this.SendPropertyChanged("numero_casa");
					this.Onnumero_casaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa_fisica", DbType="Int")]
		public System.Nullable<int> id_pessoa_fisica
		{
			get
			{
				return this._id_pessoa_fisica;
			}
			set
			{
				if ((this._id_pessoa_fisica != value))
				{
					if (this._PessoaFisica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pessoa_fisicaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa_fisica = value;
					this.SendPropertyChanged("id_pessoa_fisica");
					this.Onid_pessoa_fisicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_pessoa", DbType="Int NOT NULL")]
		public int id_tipo_pessoa
		{
			get
			{
				return this._id_tipo_pessoa;
			}
			set
			{
				if ((this._id_tipo_pessoa != value))
				{
					if (this._TipoUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tipo_pessoaChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_pessoa = value;
					this.SendPropertyChanged("id_tipo_pessoa");
					this.Onid_tipo_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_endereco", DbType="Int NOT NULL")]
		public int id_endereco
		{
			get
			{
				return this._id_endereco;
			}
			set
			{
				if ((this._id_endereco != value))
				{
					if (this._Enderecos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_enderecoChanging(value);
					this.SendPropertyChanging();
					this._id_endereco = value;
					this.SendPropertyChanged("id_endereco");
					this.Onid_enderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enderecos_Usuarios", Storage="_Enderecos", ThisKey="id_endereco", OtherKey="id", IsForeignKey=true)]
		public Enderecos Enderecos
		{
			get
			{
				return this._Enderecos.Entity;
			}
			set
			{
				Enderecos previousValue = this._Enderecos.Entity;
				if (((previousValue != value) 
							|| (this._Enderecos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Enderecos.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Enderecos.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._id_endereco = value.id;
					}
					else
					{
						this._id_endereco = default(int);
					}
					this.SendPropertyChanged("Enderecos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PessoaFisica_Usuarios", Storage="_PessoaFisica", ThisKey="id_pessoa_fisica", OtherKey="id", IsForeignKey=true)]
		public PessoaFisica PessoaFisica
		{
			get
			{
				return this._PessoaFisica.Entity;
			}
			set
			{
				PessoaFisica previousValue = this._PessoaFisica.Entity;
				if (((previousValue != value) 
							|| (this._PessoaFisica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PessoaFisica.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._PessoaFisica.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._id_pessoa_fisica = value.id;
					}
					else
					{
						this._id_pessoa_fisica = default(Nullable<int>);
					}
					this.SendPropertyChanged("PessoaFisica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_Usuarios", Storage="_TipoUsuario", ThisKey="id_tipo_pessoa", OtherKey="id", IsForeignKey=true)]
		public TipoUsuario TipoUsuario
		{
			get
			{
				return this._TipoUsuario.Entity;
			}
			set
			{
				TipoUsuario previousValue = this._TipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoUsuario.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._TipoUsuario.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._id_tipo_pessoa = value.id;
					}
					else
					{
						this._id_tipo_pessoa = default(int);
					}
					this.SendPropertyChanged("TipoUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
